metadata:
  name: prod-sector7-intermediate
  description: "Privileges for Sector-7 Intermediate Users"
  accounts:
    - prod

policy:
  Version: '2012-10-17'
  Statement:

  - Sid: ListServices
    Effect: Allow
    Action:
    - cloudwatch:DescribeAlarms
    - cloudwatch:DescribeAlarmsForMetric
    - cloudwatch:DescribeAnomalyDetectors
    - cloudwatch:GetDashboard
    - cloudwatch:ListDashboards
    - cloudwatch:ListMetrics
    - cloudwatch:ListTagsForResource
    - ec2:DescribeElasticGpus
    - ec2:DescribeScheduledInstanceAvailability
    - ec2:DescribeScheduledInstances
    - ec2:DescribeTags
    - ec2:GetConsoleOutput
    - ec2:GetConsoleScreenshot
    - eks:DescribeCluster
    - eks:DescribeFargateProfile
    - eks:DescribeNodegroup
    - eks:ListClusters
    - eks:ListFargateProfiles
    - eks:ListNodegroups
    - eks:ListTagsForResource
    - elasticache:DescribeCacheClusters
    - elasticache:DescribeCacheEngineVersions
    - elasticache:DescribeCacheParameterGroups
    - elasticache:DescribeCacheParameters
    - elasticache:DescribeCacheSecurityGroups
    - elasticache:DescribeCacheSubnetGroups
    - elasticache:DescribeEngineDefaultParameters
    - elasticache:DescribeEvents
    - elasticache:DescribeGlobalReplicationGroups
    - elasticache:DescribeReplicationGroups
    - elasticache:DescribeReservedCacheNodes
    - elasticache:DescribeReservedCacheNodesOfferings
    - elasticache:ListAllowedNodeTypeModifications
    - elasticache:ListTagsForResource
    - es:DescribeElasticsearchDomains
    - es:DescribeElasticsearchInstanceTypeLimits
    - es:DescribeInboundCrossClusterSearchConnections
    - es:DescribeOutboundCrossClusterSearchConnections
    - es:DescribeReservedElasticsearchInstanceOfferings
    - es:DescribeReservedElasticsearchInstances
    - es:GetCompatibleElasticsearchVersions
    - es:ListDomainNames
    - es:ListElasticsearchInstanceTypeDetails
    - es:ListElasticsearchInstanceTypes
    - es:ListElasticsearchVersions
    - s3:GetBucketLocation
    - s3:ListAllMyBuckets
    - sns:GetSubscriptionAttributes
    - sns:GetTopicAttributes
    - sns:ListSubscriptions
    - sns:ListSubscriptionsByTopic
    - sns:ListTagsForResource
    - sns:ListTopics
    - sqs:GetQueueAttributes
    - sqs:GetQueueUrl
    - sqs:ListDeadLetterSourceQueues
    - sqs:ListQueues
    - sqs:ListQueueTags
    Resource: "*"

  - Sid: MicroserviceQueues
    Effect: Allow
    Action:
    - sqs:ReceiveMessage
    Resource:
    - arn:aws:sqs:us-west-2:296458053855:customer-directory-service-*
    - arn:aws:sqs:us-west-2:296458053855:customer-graph-service-*
    - arn:aws:sqs:us-west-2:296458053855:customer-survey-service-*
    - arn:aws:sqs:us-west-2:296458053855:external-data-proxy-service-*
    - arn:aws:sqs:us-west-2:296458053855:funnel-service-*
    - arn:aws:sqs:us-west-2:296458053855:gmd-nav-service-*
    - arn:aws:sqs:us-west-2:296458053855:gmdnav-service-*
    - arn:aws:sqs:us-west-2:296458053855:insights-service-*
    - arn:aws:sqs:us-west-2:296458053855:milestone-service-*
    - arn:aws:sqs:us-west-2:296458053855:more-reviews-service-*
    - arn:aws:sqs:us-west-2:296458053855:partner-admin-portal-service-*
    - arn:aws:sqs:us-west-2:296458053855:reputation-defense-service-*
    - arn:aws:sqs:us-west-2:296458053855:sbo-creds-service-*
    - arn:aws:sqs:us-west-2:296458053855:transaction-component-service-*
    - arn:aws:sqs:us-west-2:296458053855:txn-component-service-*
    - arn:aws:sqs:us-west-2:296458053855:vault-file-service-*

  - Sid: RDSAccess
    Effect: Allow
    Action:
    - rds-db:connect
    Resource:
    - arn:aws:rds-db:us-west-2:888558705950:dbuser:db-BE5QLJ3373ZMJ5LP4PBXD2GTHE/readwrite_user
