version: 2.0
jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.7
    steps:
      - checkout
      - run:
          name: Install Alpine Packages
          command: apk add findutils make
      - run:
          name: Add Terraform Cloud Creds
          command: '[[ -n "$TFE_TOKEN" ]] && echo "credentials \"app.terraform.io\" {token = \"$TFE_TOKEN\"}" > ~/.terraformrc || true'
      - run:
          name: Run Test Script
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
