humans:
  adudhe:
    full_name: Ajey Dudhe
    email: adudhe@womply.com
  ahuerta:
    full_name: Anthony Huerta
    email: ahuerta@womply.com
  amishra:
    full_name: Aman Mishra
    email: amishra@womply.com
  arao:
    full_name: Abhay Rao
    email: arao@womply.com
  athakral:
    full_name: Aman Thakral
    email: athakral@womply.com
  avidekar:
    full_name: Ajay Videkar
    email: avidekar@womply.com
  babney:
    full_name: Bill Abney
    email: babney@womply.com
  blupashko:
    full_name: Bogdan Lupashko
    email: blupashko@womply.com
  bthite:
    full_name: Bipin Thite
    email: bthite@womply.com
  cmorgan:
    full_name: Tex Morgan
    email: cmorgan@womply.com
  ealva:
    full_name: Elroy Alva
    email: ealva@womply.com
  ehanig:
    full_name: Eytan Hanig
    email: ehanig@womply.com
  gthimmapuram:
    full_name: Gopal Thimmapuram
    email: gthimmapuram@womply.com
  gvidwans:
    full_name: Gaurav Vidwans
    email: gvidwans@womply.com
  jmacdonald:
    full_name: Jeff Mac
    email: jmacdonald@womply.com
  kdas:
    full_name: Kohitij Das
    email: kdas@womply.com
  linnea:
    full_name: Linnea Johnson
    email: linnea@womply.com
  mchigurupati:
    full_name: Mahesh Chigurupati
    email: mchigurupati@womply.com
  msilvey:
    full_name: Matthew Silvey
    email: msilvey@womply.com
  nabil: # Grandfathered naming convention
    full_name: Nabil Lehlou
    email: nabil@womply.com
  pdaniv:
    full_name: Pavlo Daniv
    email: pdaniv@womply.com
  ssingh:
    full_name: Shivam Singh
    email: ssingh@womply.com
  ssonwane:
    full_name: Swapnil Sonwane
    email: ssonwane@womply.com
  ubhusan:
    full_name: Uday Bhushan
    email: ubhusan@womply.com
  vgajula:
    full_name: Vinay Gajula
    email: vgajula@womply.com
  vorshulyak:
    full_name: Vlad Orshulyak
    email: vorshulyak@womply.com
